// prisma/seed-hobbies.cjs
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const hobbies = [
  // --- Social & casual meetups ---
  "Coffee Meetup",
  "Brunch Meetup",
  "Afterwork Drinks",
  "New in Town Meetup",
  "Digital Nomad Meetup",
  "Remote Workers Meetup",
  "International Students Meetup",
  "Erasmus Meetup",
  "Expats Meetup",
  "Women in Tech Meetup",
  "Startup Founders Meetup",
  "Solo Travelers Meetup",
  "Weekend Social Mixer",
  "Networking Event",
  "Speed Networking",
  "Introverts Friendly Meetup",
  "Small Talk Practice",
  "Board Game & Chill",
  "Park Picnic Meetup",
  "Cozy Cafe Hangout",

  // --- Study & co-learning / ortak ders çalışma ---
  "Study Group - General",
  "Study Group - Mathematics",
  "Study Group - Physics",
  "Study Group - Computer Science",
  "Study Group - Engineering",
  "Study Group - Programming",
  "Study Group - Data Science",
  "Study Group - AI & Machine Learning",
  "Study Group - Exam Prep",
  "Study Group - University Entrance",
  "Deep Work Session",
  "Silent Study Session",
  "Pomodoro Study Session",
  "Library Study Hangout",
  "Co-working at Cafe",
  "Co-working at Library",
  "Online Co-working Session",
  "Thesis Writing Sprint",
  "Research Paper Reading Club",
  "Journal Club",

  // --- Tech & coding ---
  "Coding Meetup",
  "Web Development Meetup",
  "Mobile Development Meetup",
  "Game Development Meetup",
  "Backend Engineering Meetup",
  "Frontend Engineering Meetup",
  "DevOps & Cloud Meetup",
  "Cybersecurity Meetup",
  "AI & Machine Learning Meetup",
  "Data Science Meetup",
  "Data Engineering Meetup",
  "Open Source Contributors Meetup",
  "Hackathon",
  "Competitive Programming Practice",
  "LeetCode Night",
  "Tech Talks & Lightning Talks",
  "Product Management Meetup",
  "UI/UX Design Meetup",
  "No-Code / Low-Code Meetup",
  "Makers & Hardware Hacking",

  // --- Board games & gaming ---
  "Board Games",
  "Strategy Board Games",
  "Party Board Games",
  "Chess Club",
  "Go / Baduk Club",
  "Card Games Night",
  "Tabletop RPG Session",
  "Dungeons & Dragons Night",
  "Trading Card Games",
  "Esports",
  "Casual Gaming",
  "LAN Party",
  "Retro Gaming Night",
  "Mobile Games Meetup",
  "Puzzle & Brain Games",
  "Board Game Design",
  "Murder Mystery Night",
  "Trivia Night",
  "Quiz Night",
  "Casino Night (Just for Fun)",

  // --- Sports & outdoor ---
  "Running",
  "Cycling",
  "Road Cycling",
  "Mountain Biking",
  "Gym / Fitness",
  "Calisthenics",
  "CrossFit",
  "Football",
  "Basketball",
  "Volleyball",
  "Beach Volleyball",
  "Tennis",
  "Table Tennis",
  "Badminton",
  "Hiking",
  "Trail Running",
  "Climbing",
  "Bouldering",
  "Swimming",
  "Open Water Swimming",
  "Yoga",
  "Pilates",
  "Functional Training",
  "Park Workout",
  "Morning Run Club",
  "Evening Walk Club",
  "Stretching & Mobility",
  "Urban Cycling Tour",
  "Skateboarding",
  "Roller Skating",
  "Skiing & Snowboarding",

  // --- Dance & movement ---
  "Dancing - Salsa",
  "Dancing - Bachata",
  "Dancing - Kizomba",
  "Dancing - Tango",
  "Dancing - Hip Hop",
  "Dancing - K-Pop",
  "Zumba",
  "Contemporary Dance",
  "Social Dance Night",
  "Dance Practice Session",

  // --- Arts, crafts & making ---
  "Painting",
  "Watercolor Painting",
  "Acrylic Painting",
  "Drawing",
  "Sketching in the City",
  "Digital Art",
  "Graphic Design Jam",
  "Calligraphy",
  "Illustration",
  "Photography",
  "Street Photography Walk",
  "Portrait Photography",
  "Film Photography",
  "Videography",
  "Content Creation Meetup",
  "YouTube Creators Meetup",
  "Podcasting Meetup",
  "3D Printing & Maker Lab",
  "Arduino & Electronics Workshop",
  "Robotics Meetup",
  "Crafts & DIY",
  "Knitting & Crochet",
  "Embroidery",
  "Handmade Jewelry Workshop",
  "Pottery & Ceramics",
  "Origami",
  "Model Building",

  // --- Music & performance ---
  "Jam Session",
  "Guitar Circle",
  "Piano Lovers Meetup",
  "Singing Circle",
  "Choir Practice",
  "Open Mic Night",
  "Karaoke Night",
  "Songwriting Circle",
  "DJ & Electronic Music Meetup",
  "Music Production Meetup",
  "Live Concert Buddy Group",
  "Street Music Jam",
  "Classical Music Appreciation",
  "Jazz Listening Session",
  "Band Practice Session",

  // --- Language & culture ---
  "Language Exchange - English",
  "Language Exchange - German",
  "Language Exchange - Turkish",
  "Language Exchange - Spanish",
  "Language Exchange - Italian",
  "Language Exchange - French",
  "Language Exchange - Mixed",
  "Coffee & Language Exchange",
  "Conversation Practice - Beginner",
  "Conversation Practice - Intermediate",
  "Conversation Practice - Advanced",
  "Book Club",
  "Non-fiction Book Club",
  "Fiction Book Club",
  "Philosophy Reading Group",
  "Culture Exchange Night",
  "Travel Stories Night",
  "Movie Night",
  "Documentary Night",
  "Anime & Manga Meetup",

  // --- Food & drink ---
  "Cooking Class",
  "Baking",
  "Dessert Workshop",
  "Barista & Coffee Workshop",
  "Tea Tasting",
  "Wine Tasting",
  "Beer Tasting",
  "Craft Beer Meetup",
  "Vegan Cooking Workshop",
  "Street Food Tour",
  "Restaurant Discovery Group",
  "International Cuisine Night",
  "Potluck Dinner",
  "Picnic & Snacks Meetup",
  "Food Photography Walk",

  // --- Wellness & mental health ---
  "Meditation",
  "Mindfulness Practice",
  "Breathwork Session",
  "Sound Healing",
  "Yoga & Meditation",
  "Morning Routine Club",
  "Gratitude Journal Circle",
  "Mental Health Support Circle",
  "Stress Relief Walk",
  "Nature Walk & Mindfulness",
  "Digital Detox Meetup",
  "Journaling Meetup",
  "Goal Setting Session",
  "Accountability Group",
  "Life Design Workshop",

  // --- Volunteering & community ---
  "Volunteering & Charity",
  "Beach Cleanup",
  "Park Cleanup",
  "Animal Shelter Volunteering",
  "Community Garden Meetup",
  "Charity Run / Walk",
  "Fundraising Events",
  "Teaching Kids Coding",
  "Mentoring Students",
  "Local Community Projects",
  "Neighborhood Meet & Greet",
  "Refugee Support Volunteers",
  "Recycling & Sustainability Meetup",
  "Climate Action Meetup",
  "Social Impact Projects",

  // --- Travel, city & exploration ---
  "City Walking Tour",
  "Hidden Spots in the City",
  "Museum & Gallery Visit",
  "Historical Sites Tour",
  "Weekend Trip Planning",
  "Backpacking Meetup",
  "Solo Travel Planning",
  "Travel Photo Walk",
  "Train Trip Meetup",
  "Nature Day Trip",

  // --- Online / hybrid specific ---
  "Online Study Group",
  "Online Coding Session",
  "Online Language Exchange",
  "Online Game Night",
  "Online Movie Night",
  "Remote Book Club",
  "Virtual Coworking",
  "Virtual Coffee Chat",
  "Online Networking Event",
  "Remote Team Building",
];

async function main() {
  console.log("⏳ Seeding hobbies...");

  for (const name of hobbies) {
    await prisma.hobby.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }

  console.log(`✅ Done. Inserted/kept ${hobbies.length} hobbies.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
